bridge:
  # immagine compressa: container A → container B
  - topic: /sensors/front_camera/color/image_raw/compressed
    type: sensor_msgs/msg/CompressedImage
    from_domain: 104
    to_domain: 105
    qos:
      reliability: best_effort
      history: keep_last
      depth: 1
      durability: volatile

  # cmd_vel: container B → container A (verso Gazebo)
  - topic: /cmd_vel
    type: geometry_msgs/msg/Twist
    from_domain: 105
    to_domain: 104
    qos:
      reliability: reliable
      history: keep_last
      depth: 10
      durability: volatile

  # /navila/action opzionale: solo se vuoi monitorarlo dal container A
  - topic: /navila/action
    type: std_msgs/msg/String
    from_domain: 105
    to_domain: 104
    qos:
      reliability: reliable
      history: keep_last
      depth: 10
      durability: volatile