navila_super_node:
  ros__parameters:
    model_path: "/models"
    inference_rate_hz: 2.0
    use_phi3: false
    phi3_4bit: true

    # sarebbe da usare e aggiornare per il launch file, terminata la fase di test
    # ma per ora lo lascio hardcoded nel codice